builds:
  - main: ./genesis/cmd/genesis
    ldflags:
      - -s -w -X github.com/interchained/genesis/genesis/internal/version.Version={{.Tag}} -X github.com/interchained/genesis/stgenesisarport/internal/version.Date={{.Date}}
    goarch:
      - amd64

brews:
  - name: "genesis"
    description: "Friendly CLI tool for developing Electronero Smart Chain SDK apps."
    homepage: "https://github.com/interchained/genesis"
    tap:
      owner: "interchained"
      name: "homebrew-tap"
    install: |
      bin.install "genesis"

