{
  "name": "{{ .User }}-{{ .Repo }}-js",
  "version": "0.1.0",
  "description": "Autogenerated XRC20 modules vuex store",
  "author": "GEnesis Starport Codegen <hello@electronero.org>",  
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "index.js",
  "publishConfig": {
    "access": "public"
  }
}